### ISSUE TITLE
please update dockerhub build

### ISSUE THREAD

**Issue by sneak** [rancherlabs/drone-plugin-golangci-lint#3]
https://hub.docker.com/r/rancher/drone-golangci-lint/tags

The last build is over 2 years ago, and doesn't use current go or current golangci-lint.

**Comment by sneak** [comment]
I've got a fork here:

https://git.eeqj.de/sneak/drone-plugin-golangci-lint

Builds are here:

https://git.eeqj.de/sneak/-/packages/container/drone-golangci-lint/2024-06-01

It's hosted on a public registry, you can use this in a .drone.yml if you like:

```
kind: pipeline
name: test-docker-build

steps:
  - name: golangci-lint
    image: git.eeqj.de/sneak/drone-golangci-lint:2024-06-01
```

It's current as of today (2024-06-01) and uses go1.22 and golangci-lint 1.59.0.
